import React, { useState, useEffect, useRef, useMemo } from 'react';
import {
  Bot,
  MessageCircle,
  Send,
  Smartphone,
  Sparkles,
  CheckCircle2,
  Clock,
  AlertCircle,
  Trash2,
  RefreshCw,
  Copy,
  Check,
  ExternalLink,
  ShoppingBag,
  Truck,
  Calendar,
  Settings,
  ShieldCheck,
  FileText,
  ChevronRight,
  Phone,
  QrCode,
  CreditCard,
  X,
  Volume2,
  Layers,
  ArrowLeft,
  Flame,
} from 'lucide-react';
import {
  Product,
  ProductVariant,
  Transaction,
  StoreSettings,
  WABotChatMessage,
  WABotConfig,
  OrderType,
} from '../../types';
import {
  formatRupiah,
  sanitizeWhatsAppNumber,
  checkStoreStatus,
  DELIVERY_MIN_ORDER_AMOUNT,
} from '../../utils/formatters';
import {
  WABotService,
  INITIAL_WABOT_SESSION,
  WABotSessionState,
} from '../../services/wabotService';
import {
  subscribeToAuditLogs,
  AuditLogEntry,
  logAuditActivity,
} from '../../services/firebase';

interface WABotManagementViewProps {
  products: Product[];
  productVariants?: ProductVariant[];
  transactions: Transaction[];
  settings: StoreSettings;
  onUpdateSettings: (newSettings: StoreSettings) => Promise<boolean>;
  onSelectTransaction?: (tx: Transaction) => void;
  showToast: (msg: string, type?: 'success' | 'error' | 'info') => void;
}

export const WABotManagementView: React.FC<WABotManagementViewProps> = ({
  products,
  productVariants = [],
  transactions,
  settings,
  onUpdateSettings,
  onSelectTransaction,
  showToast,
}) => {
  const [activeTab, setActiveTab] = useState<'simulator' | 'orders' | 'config' | 'webhook' | 'logs'>('simulator');
  const [messages, setMessages] = useState<WABotChatMessage[]>([]);
  const [inputText, setInputText] = useState('');
  const [isBotTyping, setIsBotTyping] = useState(false);
  const [session, setSession] = useState<WABotSessionState>(INITIAL_WABOT_SESSION);
  const [copiedInvoice, setCopiedInvoice] = useState<string | null>(null);
  const [auditLogs, setAuditLogs] = useState<AuditLogEntry[]>([]);
  const [isSavingConfig, setIsSavingConfig] = useState(false);

  // Form Configuration
  const [botConfig, setBotConfig] = useState<WABotConfig>(() => ({
    isEnabled: settings.wabotConfig?.isEnabled ?? true,
    botPhoneNumber: settings.wabotConfig?.botPhoneNumber || settings.whatsappNumber || '6281234567890',
    botName: settings.wabotConfig?.botName || 'WA BOT WARUNG BANG KOBRA',
    greetingMessage:
      settings.wabotConfig?.greetingMessage ||
      '👋 Halo, selamat datang di WARUNG BANG KOBRA.\n\nSaya asisten otomatis yang siap melayani pesanan Anda secara cepat & ramah!\n\nSilakan pilih menu di bawah ini:',
    closedMessage:
      settings.wabotConfig?.closedMessage ||
      'Maaf, WARUNG BANG KOBRA saat ini sedang tutup. Silakan melakukan pemesanan kembali pada jam operasional kami. Anda tetap dapat melihat menu yang tersedia.',
    orderConfirmationTemplate:
      settings.wabotConfig?.orderConfirmationTemplate ||
      '✅ Pesanan Anda berhasil dicatat dan diteruskan ke kasir!',
    deliveryTemplate:
      settings.wabotConfig?.deliveryTemplate ||
      '🛵 Pesanan delivery Anda siap diantar ke area Pesantren DQM.',
    receiptTemplate:
      settings.wabotConfig?.receiptTemplate ||
      '🧾 Struk digital resmi Warung Bang Kobra.',
    poTemplate:
      settings.wabotConfig?.poTemplate ||
      '🎉 Formulir Pre-Order Acara / Katering berhasil dibuat.',
    cashierWaLink: settings.wabotConfig?.cashierWaLink || `https://wa.me/${sanitizeWhatsAppNumber(settings.whatsappNumber || '6281234567890')}`,
    minDeliveryAmount: settings.wabotConfig?.minDeliveryAmount || settings.deliveryMinOrder || DELIVERY_MIN_ORDER_AMOUNT,
    deliveryAreaName: settings.wabotConfig?.deliveryAreaName || settings.deliveryAreaName || 'Sekitar Pesantren DQM',
    autoReplyUnknown:
      settings.wabotConfig?.autoReplyUnknown ||
      'Maaf, saya belum memahami permintaan tersebut. Silakan pilih menu di bawah atau hubungi kasir langsung.',
  }));

  const chatContainerRef = useRef<HTMLDivElement>(null);

  // Initialize bot greeting on load
  useEffect(() => {
    if (messages.length === 0) {
      setMessages([WABotService.getWelcomeMessage(settings)]);
    }
  }, [settings]);

  // Subscribe to real-time audit logs
  useEffect(() => {
    const unsub = subscribeToAuditLogs((logs) => {
      setAuditLogs(
        logs.filter(
          (l) =>
            l.action.includes('WABOT') ||
            (l.actor && l.actor.includes('WA BOT')) ||
            (l.user && l.user.includes('WA BOT'))
        )
      );
    });
    return () => unsub();
  }, []);

  // Auto scroll chat
  useEffect(() => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
    }
  }, [messages, isBotTyping]);

  // Filter Orders generated by WA Bot
  const wabotOrders = useMemo(() => {
    return transactions.filter(
      (tx) => tx.kasir === 'WA Bot Otomatis' || tx.kasir === 'WA Bot PO System' || tx.id_transaksi?.startsWith('WBK-')
    );
  }, [transactions]);

  // Handle Send Message in Simulator
  const handleSendMessage = async (customText?: string) => {
    const text = (customText || inputText).trim();
    if (!text || isBotTyping) return;

    // Add user message
    const userMsg: WABotChatMessage = {
      id: `msg-${Date.now()}`,
      sender: 'user',
      text,
      timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
    };

    setMessages((prev) => [...prev, userMsg]);
    setInputText('');
    setIsBotTyping(true);

    // Simulate natural typing delay (400ms - 800ms)
    setTimeout(async () => {
      await processBotResponse(text);
      setIsBotTyping(false);
    }, 550);
  };

  // Bot Logic Engine
  const processBotResponse = async (input: string) => {
    const cleanInput = input.trim().toLowerCase();
    const storeStatus = checkStoreStatus(settings);

    // 0. RESET / MENU / HOME
    if (cleanInput === 'menu' || cleanInput === 'halo' || cleanInput === 'hai' || cleanInput === 'batal' || cleanInput === 'home') {
      setSession(INITIAL_WABOT_SESSION);
      setMessages((prev) => [...prev, WABotService.getWelcomeMessage(settings)]);
      return;
    }

    // 1. LIHAT MENU
    if (cleanInput === '1' || cleanInput.includes('lihat menu') || cleanInput.includes('katalog')) {
      const catalogMsg = WABotService.getMenuCatalogMessage(products, productVariants);
      setMessages((prev) => [...prev, catalogMsg]);
      return;
    }

    // Filter kategori menu
    if (cleanInput.startsWith('filter_')) {
      const cat = input.split('_')[1];
      const catalogMsg = WABotService.getMenuCatalogMessage(products, productVariants, cat);
      setMessages((prev) => [...prev, catalogMsg]);
      return;
    }

    // 2. PESAN SEKARANG
    if (cleanInput === '2' || cleanInput.includes('pesan sekarang') || cleanInput === 'pesan_delivery' || cleanInput === 'pesan_takeaway') {
      if (!storeStatus.isOpen) {
        setMessages((prev) => [
          ...prev,
          {
            id: `msg-${Date.now()}`,
            sender: 'bot',
            text: `⚠️ *Mohon Maaf, WARUNG BANG KOBRA Saat Ini Tutup*\n\n${storeStatus.reason}\n\nSilakan melakukan pemesanan kembali saat toko buka (${storeStatus.scheduleText || '08:00 - 22:00 WIB'}). Namun Anda tetap dapat melihat menu.`,
            timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
            quickReplies: [
              { id: 'qr-menu', label: '1️⃣ Lihat Menu', payload: '1' },
              { id: 'qr-kasir', label: '6️⃣ Hubungi Kasir', payload: '6' },
            ],
          },
        ]);
        return;
      }

      const initialType: OrderType = cleanInput === 'pesan_delivery' ? 'DELIVERY_DQM' : 'BUNGKUS';
      setSession((prev) => ({
        ...INITIAL_WABOT_SESSION,
        orderType: initialType,
        step: 'SELECTING_PRODUCT',
      }));

      // Render product choice
      const available = products.filter((p) => p.status !== 'Nonaktif' && p.stok > 0);
      const buttons = available.slice(0, 10).map((p) => ({
        id: `prod-${p.id}`,
        label: `${p.nama} (${formatRupiah(p.harga_jual)})`,
        payload: `pilih_produk_${p.id}`,
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `Silakan pilih produk yang ingin Anda pesan (klik tombol atau ketik nama menu):`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
          quickReplies: buttons,
        },
      ]);
      return;
    }

    // Product Selection
    if (cleanInput.startsWith('pilih_produk_') || session.step === 'SELECTING_PRODUCT') {
      let selectedProduct: Product | undefined;

      if (cleanInput.startsWith('pilih_produk_')) {
        const prodId = input.replace('pilih_produk_', '');
        selectedProduct = products.find((p) => p.id === prodId);
      } else {
        selectedProduct = products.find((p) => p.nama.toLowerCase().includes(cleanInput));
      }

      if (!selectedProduct) {
        setMessages((prev) => [
          ...prev,
          {
            id: `msg-${Date.now()}`,
            sender: 'bot',
            text: `Menu tidak ditemukan atau stok habis. Silakan ketik nama menu yang ada di daftar menu atau pilih tombol di bawah:`,
            timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
            quickReplies: products
              .filter((p) => p.stok > 0)
              .slice(0, 8)
              .map((p) => ({
                id: `qr-p-${p.id}`,
                label: p.nama,
                payload: `pilih_produk_${p.id}`,
              })),
          },
        ]);
        return;
      }

      if (selectedProduct.stok <= 0) {
        setMessages((prev) => [
          ...prev,
          {
            id: `msg-${Date.now()}`,
            sender: 'bot',
            text: `❌ Mohon maaf, menu *${selectedProduct?.nama}* sedang *HABIS*. Silakan pilih menu lainnya.`,
            timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
          },
        ]);
        return;
      }

      const prodVariants = productVariants.filter((v) => v.productId === selectedProduct?.id && v.isActive);

      if (prodVariants.length > 0) {
        setSession((prev) => ({
          ...prev,
          currentProduct: selectedProduct,
          step: 'SELECTING_VARIANT',
        }));

        setMessages((prev) => [
          ...prev,
          {
            id: `msg-${Date.now()}`,
            sender: 'bot',
            text: `Pilih varian rasa / topping untuk *${selectedProduct?.nama}*:`,
            timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
            quickReplies: prodVariants.map((v) => ({
              id: `var-${v.variantId}`,
              label: `${v.variantName} (+${formatRupiah(v.price)})`,
              payload: `pilih_varian_${v.variantId}`,
            })),
          },
        ]);
        return;
      }

      // No variants, ask quantity
      setSession((prev) => ({
        ...prev,
        currentProduct: selectedProduct,
        currentVariant: undefined,
        step: 'SELECTING_QTY',
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `Berapa jumlah (porsi) untuk *${selectedProduct?.nama}*? (Ketik angka atau pilih):`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
          quickReplies: [
            { id: 'qty-1', label: '1 Porsi', payload: '1' },
            { id: 'qty-2', label: '2 Porsi', payload: '2' },
            { id: 'qty-3', label: '3 Porsi', payload: '3' },
            { id: 'qty-5', label: '5 Porsi', payload: '5' },
          ],
        },
      ]);
      return;
    }

    // Variant Selection
    if (session.step === 'SELECTING_VARIANT' && (cleanInput.startsWith('pilih_varian_') || cleanInput)) {
      let selectedVar: ProductVariant | undefined;
      const prodVariants = productVariants.filter((v) => v.productId === session.currentProduct?.id && v.isActive);

      if (cleanInput.startsWith('pilih_varian_')) {
        const vid = input.replace('pilih_varian_', '');
        selectedVar = prodVariants.find((v) => v.variantId === vid);
      } else {
        selectedVar = prodVariants.find((v) => v.variantName.toLowerCase().includes(cleanInput));
      }

      const activeVar = selectedVar || prodVariants[0];

      setSession((prev) => ({
        ...prev,
        currentVariant: activeVar,
        step: 'SELECTING_QTY',
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `Varian *${activeVar?.variantName}* dipilih. Berapa porsi yang dipesan?`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
          quickReplies: [
            { id: 'qty-1', label: '1 Porsi', payload: '1' },
            { id: 'qty-2', label: '2 Porsi', payload: '2' },
            { id: 'qty-3', label: '3 Porsi', payload: '3' },
          ],
        },
      ]);
      return;
    }

    // Quantity Input
    if (session.step === 'SELECTING_QTY') {
      const qtyNum = parseInt(cleanInput, 10);
      if (isNaN(qtyNum) || qtyNum <= 0) {
        setMessages((prev) => [
          ...prev,
          {
            id: `msg-${Date.now()}`,
            sender: 'bot',
            text: `Mohon masukkan jumlah porsi berupa angka yang valid (contoh: *1*, *2*, *5*):`,
            timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
          },
        ]);
        return;
      }

      setSession((prev) => ({
        ...prev,
        tempQty: qtyNum,
        step: 'ADDING_NOTES',
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `Ada catatan khusus untuk menu ini? (Misal: *"Pedas level 3"*, *"Es dipisah"*, atau ketik *-* jika tidak ada):`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
          quickReplies: [
            { id: 'note-none', label: 'Tanpa Catatan (-)', payload: '-' },
            { id: 'note-pedas', label: 'Pedas Mantap', payload: 'Pedas Mantap' },
            { id: 'note-sedang', label: 'Pedas Sedang', payload: 'Pedas Sedang' },
          ],
        },
      ]);
      return;
    }

    // Notes Input & Cart Update
    if (session.step === 'ADDING_NOTES') {
      const note = cleanInput === '-' ? '' : input.trim();
      const product = session.currentProduct!;
      const variant = session.currentVariant;
      const qty = session.tempQty || 1;
      const unitPrice = variant ? variant.price : product.harga_jual;
      const subtotal = unitPrice * qty;

      const newCartItem = {
        product,
        variant,
        qty,
        notes: note,
        subtotal,
      };

      const updatedCart = [...session.cart, newCartItem];
      const totalBelanja = updatedCart.reduce((acc, c) => acc + c.subtotal, 0);

      setSession((prev) => ({
        ...prev,
        cart: updatedCart,
        currentProduct: undefined,
        currentVariant: undefined,
        tempQty: undefined,
        step: 'SELECTING_SERVICE_TYPE',
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `✅ *${product.nama}${variant ? ` (${variant.variantName})` : ''}* x${qty} berhasil ditambahkan!
Total sementara: *${formatRupiah(totalBelanja)}*

Apakah ingin menambah menu lain atau langsung lanjut pilih layanan?`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
          quickReplies: [
            { id: 'qr-add-more', label: '➕ Tambah Menu Lain', payload: '2' },
            { id: 'qr-service-takeaway', label: '📦 Ambil di Warung (Takeaway)', payload: 'layanan_takeaway' },
            { id: 'qr-service-delivery', label: '🛵 Delivery Pesantren DQM', payload: 'layanan_delivery' },
          ],
        },
      ]);
      return;
    }

    // Service Selection
    if (cleanInput === 'layanan_takeaway' || cleanInput === 'layanan_delivery' || session.step === 'SELECTING_SERVICE_TYPE') {
      const isDeliv = cleanInput === 'layanan_delivery';
      const orderType: OrderType = isDeliv ? 'DELIVERY_DQM' : 'BUNGKUS';
      const minDelivery = settings.deliveryMinOrder || DELIVERY_MIN_ORDER_AMOUNT;
      const totalBelanja = session.cart.reduce((sum, item) => sum + item.subtotal, 0);

      if (isDeliv && totalBelanja < minDelivery) {
        setMessages((prev) => [
          ...prev,
          {
            id: `msg-${Date.now()}`,
            sender: 'bot',
            text: `⚠️ *Minimal Belanja Delivery Belum Terpenuhi*\n\nTotal belanja saat ini: *${formatRupiah(totalBelanja)}*\nMinimal belanja delivery DQM: *${formatRupiah(minDelivery)}*\nKurang: *${formatRupiah(minDelivery - totalBelanja)}* lagi.\n\nSilakan klik *Tambah Menu Lain* atau pilih *Ambil di Warung (Tanpa Minimal)*.`,
            timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
            quickReplies: [
              { id: 'qr-add-more', label: '➕ Tambah Menu Lagi', payload: '2' },
              { id: 'qr-switch-takeaway', label: '📦 Ganti ke Bungkus / Ambil Sendiri', payload: 'layanan_takeaway' },
            ],
          },
        ]);
        return;
      }

      setSession((prev) => ({
        ...prev,
        orderType,
        step: isDeliv ? 'ASKING_DELIVERY_LOCATION' : 'ASKING_CUSTOMER_NAME',
      }));

      if (isDeliv) {
        setMessages((prev) => [
          ...prev,
          {
            id: `msg-${Date.now()}`,
            sender: 'bot',
            text: `🛵 Layanan Delivery dipilih. Silakan pilih gedung / asrama pengantaran di Pesantren DQM:`,
            timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
            quickReplies: [
              { id: 'loc-1', label: 'Asrama Putra DQM', payload: 'lokasi_Asrama Putra DQM' },
              { id: 'loc-2', label: 'Asrama Putri DQM', payload: 'lokasi_Asrama Putri DQM' },
              { id: 'loc-3', label: 'Gedung Sekolah / Kelas', payload: 'lokasi_Gedung Sekolah / Kelas' },
              { id: 'loc-4', label: 'Masjid / Aula DQM', payload: 'lokasi_Masjid / Aula DQM' },
              { id: 'loc-5', label: 'Kantor / Sekretariat', payload: 'lokasi_Kantor / Sekretariat' },
            ],
          },
        ]);
        return;
      }

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `📦 Layanan Bungkus (Ambil di Warung). Siapa nama pemesan untuk panggilan antrian?`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
      return;
    }

    // Delivery Location Selection
    if (session.step === 'ASKING_DELIVERY_LOCATION') {
      const loc = cleanInput.startsWith('lokasi_') ? input.replace('lokasi_', '') : input.trim();
      setSession((prev) => ({
        ...prev,
        deliveryLocation: loc,
        step: 'ASKING_DELIVERY_DETAIL',
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `Lokasi: *${loc}* tercatat. Mohon sebutkan detail kamar / patokan lokasi (contoh: *"Lantai 2 Kamar Abu Bakar"*):`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
      return;
    }

    // Delivery Detail
    if (session.step === 'ASKING_DELIVERY_DETAIL') {
      setSession((prev) => ({
        ...prev,
        deliveryDetail: input.trim(),
        step: 'ASKING_CUSTOMER_NAME',
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `Siapa nama penerima paket pengantaran?`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
      return;
    }

    // Customer Name
    if (session.step === 'ASKING_CUSTOMER_NAME') {
      setSession((prev) => ({
        ...prev,
        customerName: input.trim(),
        step: 'ASKING_CUSTOMER_PHONE',
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `Berapa nomor WhatsApp aktif Anda untuk konfirmasi pesanan? (Contoh: *081234567890*):`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
      return;
    }

    // Customer Phone
    if (session.step === 'ASKING_CUSTOMER_PHONE') {
      const phone = sanitizeWhatsAppNumber(input.trim());
      setSession((prev) => ({
        ...prev,
        customerPhone: phone || input.trim(),
        step: 'SELECTING_PAYMENT',
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `Pilih metode pembayaran:`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
          quickReplies: [
            { id: 'pay-cash', label: '💵 CASH / Tunai', payload: 'bayar_Cash' },
            { id: 'pay-transfer', label: '🏦 Transfer Bank (BCA)', payload: 'bayar_Transfer' },
            { id: 'pay-qris', label: '📱 QRIS Dinamis', payload: 'bayar_QRIS' },
          ],
        },
      ]);
      return;
    }

    // Payment Selection & Order Confirmation Prompt
    if (cleanInput.startsWith('bayar_') || session.step === 'SELECTING_PAYMENT') {
      const payMethod = cleanInput.startsWith('bayar_') ? input.replace('bayar_', '') : input.trim();
      const updatedSession: WABotSessionState = {
        ...session,
        paymentMethod: payMethod,
        step: 'CONFIRMATION',
      };
      setSession(updatedSession);

      const tempInvoiceId = WABotService.generateInvoiceId();
      const summaryText = WABotService.formatOrderSummary(updatedSession, settings, tempInvoiceId);

      let paymentGuide = '';
      if (payMethod.toLowerCase() === 'transfer') {
        paymentGuide = `\n\n🏦 *Info Rekening Toko:*\nBank: *${settings.bankName || 'BCA'}*\nNo. Rek: *${settings.bankAccountNumber || '8830192831'}*\nAtas Nama: *${settings.bankAccountHolder || 'Warung Bang Kobra'}*`;
      } else if (payMethod.toLowerCase() === 'qris') {
        paymentGuide = `\n\n📱 *QRIS Resmi Toko:*\nScan QRIS yang tampil di struk atau mintalah konfirmasi kasir saat pesanan diproses.`;
      }

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `${summaryText}${paymentGuide}\n\nApakah pesanan sudah benar dan siap dikirim ke kasir?`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
          quickReplies: [
            { id: 'conf-yes', label: '✅ KONFIRMASI PESANAN', payload: `confirm_order_${tempInvoiceId}` },
            { id: 'conf-edit', label: '✏️ EDIT PESANAN', payload: '2' },
            { id: 'conf-cancel', label: '❌ BATALKAN', payload: 'batal' },
          ],
        },
      ]);
      return;
    }

    // Final Order Submission
    if (cleanInput.startsWith('confirm_order_')) {
      const invoiceId = input.replace('confirm_order_', '');

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `⏳ *Sedang mengirim pesanan Anda ke Antrian Kasir...*`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
        },
      ]);

      const submitRes = await WABotService.submitOrderToFirebase(session, settings, invoiceId);

      if (submitRes.success && submitRes.order) {
        setSession(INITIAL_WABOT_SESSION);
        showToast(`Pesanan ${invoiceId} berhasil tercatat realtime!`, 'success');

        const successText = `🎉 *PESANAN BERHASIL DITERIMA KASIR!*
No. Pesanan: *${invoiceId}*
Status Awal: 🟡 *MENUNGGU KONFIRMASI*
Pemesan: *${submitRes.order.nama_pelanggan}*
Total: *${formatRupiah(submitRes.order.total)}*

🔔 Kasir kami sedang menyiapkan pesanan Anda. Anda dapat mengecek status kapan saja dengan mengetik nomor pesanan atau klik *Cek Status Pesanan* di bawah.`;

        setMessages((prev) => [
          ...prev,
          {
            id: `msg-${Date.now()}`,
            sender: 'bot',
            text: successText,
            timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
            quickReplies: [
              { id: 'qr-check-now', label: '📋 Cek Status Pesanan Ini', payload: `status_${invoiceId}` },
              { id: 'qr-home', label: '🏠 Menu Utama', payload: 'menu' },
            ],
          },
        ]);
        return;
      } else {
        setMessages((prev) => [
          ...prev,
          {
            id: `msg-${Date.now()}`,
            sender: 'bot',
            text: `❌ *Pesanan Gagal Dikirim:* ${submitRes.error || 'Terjadi gangguan jaringan database.'}\n\nSilakan coba lagi atau hubungi kasir secara langsung.`,
            timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
            quickReplies: [
              { id: 'qr-retry', label: '🔄 Coba Lagi', payload: `confirm_order_${invoiceId}` },
              { id: 'qr-kasir', label: '👨💼 Hubungi Kasir', payload: '6' },
            ],
          },
        ]);
        return;
      }
    }

    // 3. CEK STATUS PESANAN
    if (cleanInput === '3' || cleanInput.includes('cek status') || cleanInput.includes('status pesanan') || cleanInput.startsWith('status_')) {
      if (cleanInput.startsWith('status_')) {
        const queryId = input.replace('status_', '');
        const resMsg = WABotService.checkOrderStatus(queryId, transactions);
        setMessages((prev) => [...prev, resMsg]);
        return;
      }

      setSession((prev) => ({ ...prev, step: 'CHECKING_STATUS' }));
      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `🔍 Silakan ketik *Nomor Pesanan* Anda (contoh: *WBK-20261006-1234*) atau ketik *Nomor WhatsApp* yang digunakan saat memesan:`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
      return;
    }

    if (session.step === 'CHECKING_STATUS') {
      const resMsg = WABotService.checkOrderStatus(input, transactions);
      setSession((prev) => ({ ...prev, step: 'IDLE' }));
      setMessages((prev) => [...prev, resMsg]);
      return;
    }

    // 4. INFO DELIVERY
    if (cleanInput === '4' || cleanInput.includes('info delivery') || cleanInput.includes('ongkir')) {
      const delivInfoMsg = WABotService.getDeliveryInfoMessage(settings);
      setMessages((prev) => [...prev, delivInfoMsg]);
      return;
    }

    // 5. PESANAN ACARA / PO (PRE-ORDER)
    if (cleanInput === '5' || cleanInput.includes('pesanan acara') || cleanInput.includes('pre order') || cleanInput.includes('po')) {
      setSession((prev) => ({
        ...prev,
        step: 'PO_NAME',
        poData: {
          name: '',
          phone: '',
          date: '',
          time: '',
          location: '',
          guests: 20,
          menuDesc: '',
        },
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `🎉 *LAYANAN PRE-ORDER & KATERING ACARA WARUNG BANG KOBRA*

Kami siap melayani kebutuhan konsumsi acara rapat, syukuran, kajian, buka puasa bersama, dan santri DQM.

Siapa nama penanggung jawab / pemesan acara?`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
      return;
    }

    // PO Step 1: Name
    if (session.step === 'PO_NAME') {
      setSession((prev) => ({
        ...prev,
        step: 'PO_PHONE',
        poData: { ...prev.poData!, name: input.trim() },
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `Nomor WhatsApp aktif Anda untuk konfirmasi Pre-Order?`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
      return;
    }

    // PO Step 2: Phone
    if (session.step === 'PO_PHONE') {
      setSession((prev) => ({
        ...prev,
        step: 'PO_DATE',
        poData: { ...prev.poData!, phone: input.trim() },
      }));

      const tomorrow = new Date();
      tomorrow.setDate(tomorrow.getDate() + 1);
      const tomorrowStr = tomorrow.toISOString().split('T')[0];

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `Kapan tanggal pelaksanaan acara? (Contoh: *${tomorrowStr}*):`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
      return;
    }

    // PO Step 3: Date
    if (session.step === 'PO_DATE') {
      setSession((prev) => ({
        ...prev,
        step: 'PO_TIME',
        poData: { ...prev.poData!, date: input.trim() },
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `Pukul berapa hidangan harus siap / diantar? (Contoh: *11:30* WIB):`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
      return;
    }

    // PO Step 4: Time
    if (session.step === 'PO_TIME') {
      setSession((prev) => ({
        ...prev,
        step: 'PO_LOCATION',
        poData: { ...prev.poData!, time: input.trim() },
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `Di mana lokasi pengantaran / pengambilan acara? (Contoh: *Aula Utama Pesantren DQM*):`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
      return;
    }

    // PO Step 5: Location
    if (session.step === 'PO_LOCATION') {
      setSession((prev) => ({
        ...prev,
        step: 'PO_GUESTS',
        poData: { ...prev.poData!, location: input.trim() },
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `Berapa perkiraan jumlah porsi / orang? (Ketik angka, misal: *50*):`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
          quickReplies: [
            { id: 'p-20', label: '20 Porsi', payload: '20' },
            { id: 'p-50', label: '50 Porsi', payload: '50' },
            { id: 'p-100', label: '100 Porsi', payload: '100' },
          ],
        },
      ]);
      return;
    }

    // PO Step 6: Guests
    if (session.step === 'PO_GUESTS') {
      const guests = parseInt(cleanInput, 10) || 20;
      setSession((prev) => ({
        ...prev,
        step: 'PO_MENU',
        poData: { ...prev.poData!, guests },
      }));

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `Rencana paket menu yang diinginkan? (Contoh: *"Nasi Kotak Ayam Sambal Kobra + Es Teh Manis"*):`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
      return;
    }

    // PO Step 7: Menu -> Confirm
    if (session.step === 'PO_MENU') {
      const poData = { ...session.poData!, menuDesc: input.trim(), budget: (session.poData?.guests || 20) * 15000 };
      setSession((prev) => ({
        ...prev,
        step: 'PO_CONFIRMATION',
        poData,
      }));

      const summaryPO = `📋 *RINGKASAN FORMULIR PRE-ORDER ACARA*
Nama: *${poData.name}*
WhatsApp: *${poData.phone}*
Tanggal: *${poData.date}* · Pukul *${poData.time}* WIB
Lokasi: *${poData.location}*
Jumlah Porsi: *${poData.guests} Orang*
Paket Menu: *${poData.menuDesc}*
Estimasi Anggaran: *${formatRupiah(poData.budget)}* (DP 50%: ${formatRupiah(poData.budget * 0.5)})

Kirim formulir ini ke Tim Katering Warung Bang Kobra sekarang?`;

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: summaryPO,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
          quickReplies: [
            { id: 'po-send', label: '✅ Kirim Formulir PO', payload: 'kirim_po_sekarang' },
            { id: 'po-cancel', label: '❌ Batalkan', payload: 'batal' },
          ],
        },
      ]);
      return;
    }

    // PO Submission
    if (cleanInput === 'kirim_po_sekarang' && session.poData) {
      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text: `⏳ *Menyimpan Formulir Pre-Order ke Dashboard Toko...*`,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
        },
      ]);

      const poRes = await WABotService.submitPOToFirebase(session.poData, settings);

      if (poRes.success) {
        setSession(INITIAL_WABOT_SESSION);
        showToast('Pre-Order Acara berhasil disimpan!', 'success');

        const successText = `🎉 *FORMULIR PRE-ORDER BERHASIL DITERIMA!*
No. PO: *${poRes.poId}*
Status: 🟡 *MENUNGGU KONFIRMASI OWNER/ADMIN*

Tim kami akan segera menghubungi Anda via WhatsApp di *${session.poData.phone}* untuk finalisasi rincian menu dan pembayaran uang muka (DP). Terima kasih!`;

        setMessages((prev) => [
          ...prev,
          {
            id: `msg-${Date.now()}`,
            sender: 'bot',
            text: successText,
            timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
            quickReplies: [
              { id: 'qr-home', label: '🏠 Menu Utama', payload: 'menu' },
              { id: 'qr-kasir', label: '👨💼 Hubungi Kasir', payload: '6' },
            ],
          },
        ]);
        return;
      }
    }

    // 6. HUBUNGI KASIR
    if (cleanInput === '6' || cleanInput.includes('hubungi kasir') || cleanInput.includes('kasir') || cleanInput.includes('admin')) {
      const waNumber = sanitizeWhatsAppNumber(settings.whatsappNumber || '6281234567890');
      const waLink = `https://wa.me/${waNumber}?text=${encodeURIComponent('Halo Kasir Warung Bang Kobra, saya ingin bertanya tentang pesanan...')}`;

      const text = `👨💼 *LAYANAN BANTUAN KASIR & OWNER*

Anda dapat langsung terhubung dengan kasir resmi Warung Bang Kobra melalui tautan WhatsApp berikut:

👉 *WhatsApp Kasir:* [Klik di Sini untuk Chat](${waLink})
📞 *Nomor Resmi:* +${waNumber}

Kasir kami siap membantu pertanyaan pesanan khusus, perubahan pesanan, atau konfirmasi pembayaran transfer.`;

      setMessages((prev) => [
        ...prev,
        {
          id: `msg-${Date.now()}`,
          sender: 'bot',
          text,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
          quickReplies: [
            { id: 'qr-home', label: '🏠 Menu Utama', payload: 'menu' },
          ],
        },
      ]);
      return;
    }

    // DEFAULT FALLBACK (Ramah & Tidak Halusinasi)
    const fallbackText = `${botConfig.autoReplyUnknown || 'Maaf, saya belum memahami permintaan tersebut.'}\n\nSilakan pilih salah satu opsi di bawah ini:`;

    setMessages((prev) => [
      ...prev,
      {
        id: `msg-${Date.now()}`,
        sender: 'bot',
        text: fallbackText,
        timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
        quickReplies: [
          { id: 'qr-menu', label: '1️⃣ Lihat Menu', payload: '1' },
          { id: 'qr-order', label: '2️⃣ Pesan Sekarang', payload: '2' },
          { id: 'qr-status', label: '3️⃣ Cek Status Pesanan', payload: '3' },
          { id: 'qr-kasir', label: '6️⃣ Hubungi Kasir', payload: '6' },
        ],
      },
    ]);
  };

  // Handle Save Configuration
  const handleSaveBotConfig = async () => {
    setIsSavingConfig(true);
    try {
      const updatedSettings: StoreSettings = {
        ...settings,
        wabotEnabled: botConfig.isEnabled,
        wabotConfig: botConfig,
      };

      const success = await onUpdateSettings(updatedSettings);
      if (success) {
        showToast('Konfigurasi WA Bot berhasil disimpan ke Firestore!', 'success');
        logAuditActivity(
          'WABOT_CONFIG_UPDATE',
          `Memperbarui konfigurasi WA Bot (${botConfig.botName})`,
          'Admin',
          'SETTINGS'
        ).catch(() => {});
      } else {
        showToast('Gagal menyimpan konfigurasi.', 'error');
      }
    } catch (e: any) {
      showToast('Error: ' + e?.message, 'error');
    } finally {
      setIsSavingConfig(false);
    }
  };

  return (
    <div className="flex-1 flex flex-col min-h-0 bg-stone-950 text-stone-100 overflow-hidden">
      {/* 1. TOP HEADER */}
      <header className="bg-stone-900 border-b border-stone-800 px-4 py-3 shrink-0 flex flex-col sm:flex-row sm:items-center justify-between gap-3 z-10">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-emerald-600 to-green-600 flex items-center justify-center text-white shadow-lg shadow-emerald-950/60 font-black">
            <MessageCircle className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="font-black text-lg sm:text-xl text-white tracking-tight">
                WA BOT WARUNG BANG KOBRA
              </h1>
              <span className="inline-flex items-center gap-1 text-[10px] font-black uppercase tracking-wider px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-400 border border-emerald-500/30">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                ONLINE CLOUD
              </span>
            </div>
            <p className="text-[11px] text-stone-400 font-medium">
              Asisten Otomatis WhatsApp Pelanggan · Terhubung Realtime dengan Kasir &amp; Dapur
            </p>
          </div>
        </div>

        {/* Global Action Chips */}
        <div className="flex items-center gap-2 self-end sm:self-auto flex-wrap">
          <button
            type="button"
            onClick={() => {
              setSession(INITIAL_WABOT_SESSION);
              setMessages([WABotService.getWelcomeMessage(settings)]);
              showToast('Simulator WA Bot di-reset ke pesan awal.', 'info');
            }}
            className="min-h-[38px] px-3 rounded-xl bg-stone-800 hover:bg-stone-750 text-stone-300 text-xs font-bold flex items-center gap-1.5 transition cursor-pointer"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            <span>Reset Chat</span>
          </button>

          <a
            href={`https://wa.me/${sanitizeWhatsAppNumber(settings.whatsappNumber || '6281234567890')}`}
            target="_blank"
            rel="noopener noreferrer"
            className="min-h-[38px] px-3.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold flex items-center gap-1.5 shadow-lg shadow-emerald-950/50 transition cursor-pointer"
          >
            <ExternalLink className="w-3.5 h-3.5" />
            <span>Buka WhatsApp Web</span>
          </a>
        </div>
      </header>

      {/* 2. SUB NAVIGATION TABS */}
      <div className="bg-stone-920 border-b border-stone-800 px-4 py-2 shrink-0 flex items-center gap-1.5 overflow-x-auto scrollbar-none">
        {[
          { id: 'simulator', label: '📱 Live Simulator WA (Chat)', icon: Smartphone },
          { id: 'orders', label: `📦 Pesanan Masuk (${wabotOrders.length})`, icon: ShoppingBag, badge: wabotOrders.filter((o) => o.status === 'Pending' || o.status === 'MENUNGGU').length },
          { id: 'config', label: '⚙️ Konfigurasi & Template', icon: Settings },
          { id: 'webhook', label: '🌐 Integrasi Gateway & Webhook', icon: ShieldCheck },
          { id: 'logs', label: `📜 Log Aktivitas (${auditLogs.length})`, icon: FileText },
        ].map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              type="button"
              onClick={() => setActiveTab(tab.id as any)}
              className={`min-h-[38px] px-3.5 rounded-xl text-xs font-bold flex items-center gap-2 whitespace-nowrap transition cursor-pointer ${
                isActive
                  ? 'bg-gradient-to-r from-emerald-600 to-green-600 text-white shadow-md shadow-emerald-950/60'
                  : 'bg-stone-900 border border-stone-800 text-stone-400 hover:text-stone-200 hover:bg-stone-850'
              }`}
            >
              <Icon className="w-4 h-4" />
              <span>{tab.label}</span>
              {typeof tab.badge === 'number' && tab.badge > 0 && (
                <span className="w-5 h-5 rounded-full bg-red-600 text-white text-[10px] font-black flex items-center justify-center">
                  {tab.badge}
                </span>
              )}
            </button>
          );
        })}
      </div>

      {/* 3. MAIN WORKSPACE */}
      <div className="flex-1 flex min-h-0 overflow-hidden p-3 sm:p-4 lg:p-6">
        {/* ========================================================
            TAB 1: LIVE SIMULATOR WA BOT
           ======================================================== */}
        {activeTab === 'simulator' && (
          <div className="flex-1 flex flex-col lg:flex-row gap-4 max-w-6xl mx-auto w-full min-h-0">
            {/* Phone Simulator Frame */}
            <div className="flex-1 flex flex-col bg-stone-900 border border-stone-800 rounded-[28px] overflow-hidden shadow-2xl min-h-0 max-h-[85vh]">
              {/* WhatsApp Phone Mock Header */}
              <div className="bg-[#1f2c34] px-4 py-3 border-b border-[#2a3942] flex items-center justify-between text-white shrink-0">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-emerald-600 flex items-center justify-center font-black shadow relative">
                    <img
                      src={settings.logoUrl || '/icon.svg'}
                      alt="Avatar"
                      className="w-full h-full rounded-full object-cover p-0.5"
                      onError={(e) => {
                        (e.currentTarget as HTMLImageElement).src = '/icon.svg';
                      }}
                    />
                    <span className="w-3 h-3 rounded-full bg-emerald-400 border-2 border-[#1f2c34] absolute bottom-0 right-0" />
                  </div>
                  <div>
                    <h2 className="text-sm font-bold text-white leading-tight">
                      {botConfig.botName}
                    </h2>
                    <p className="text-[10px] text-emerald-400 font-medium">
                      Akun Resmi Bisnis · Online
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 font-bold border border-emerald-500/30">
                    Live Simulator
                  </span>
                </div>
              </div>

              {/* Chat Message Scrollable Viewport */}
              <div
                ref={chatContainerRef}
                className="flex-1 overflow-y-auto p-3 sm:p-4 space-y-3 bg-[#0b141a] bg-opacity-95"
                style={{
                  backgroundImage:
                    'radial-gradient(circle at 50% 50%, rgba(18, 140, 126, 0.05) 0%, transparent 80%)',
                }}
              >
                <div className="text-center my-2">
                  <span className="text-[10px] text-stone-400 bg-[#182229] px-3 py-1 rounded-full border border-stone-800 inline-block shadow-sm">
                    🔒 Pesan ini terenkripsi &amp; terhubung langsung ke sistem Warung Bang Kobra
                  </span>
                </div>

                {messages.map((msg) => {
                  const isUser = msg.sender === 'user';
                  return (
                    <div
                      key={msg.id}
                      className={`flex flex-col ${isUser ? 'items-end' : 'items-start'} animate-in fade-in`}
                    >
                      <div
                        className={`max-w-[85%] sm:max-w-[75%] rounded-2xl p-3 sm:p-3.5 shadow-md text-xs sm:text-sm leading-relaxed whitespace-pre-wrap ${
                          isUser
                            ? 'bg-[#005c4b] text-[#e9edef] rounded-br-none'
                            : 'bg-[#202c33] text-[#d1d7db] rounded-bl-none border border-[#2a3942]'
                        }`}
                      >
                        {msg.text}

                        <div className="flex items-center justify-end gap-1 text-[10px] text-stone-400 mt-1 select-none">
                          <span>{msg.timestamp}</span>
                          {isUser && <span className="text-emerald-400 font-bold">✓✓</span>}
                        </div>
                      </div>

                      {/* Quick Replies Interactive Chips */}
                      {msg.quickReplies && msg.quickReplies.length > 0 && (
                        <div className="flex flex-wrap gap-1.5 mt-2 max-w-[85%] sm:max-w-[75%]">
                          {msg.quickReplies.map((qr) => (
                            <button
                              key={qr.id}
                              type="button"
                              onClick={() => handleSendMessage(qr.payload)}
                              className="px-3 py-1.5 rounded-full bg-[#1f2c34] hover:bg-[#2a3942] text-emerald-400 hover:text-emerald-300 border border-emerald-500/40 text-xs font-bold transition active:scale-95 shadow cursor-pointer"
                            >
                              {qr.label}
                            </button>
                          ))}
                        </div>
                      )}
                    </div>
                  );
                })}

                {/* Bot Typing Indicator */}
                {isBotTyping && (
                  <div className="flex items-center gap-1.5 bg-[#202c33] border border-[#2a3942] w-20 px-3 py-2 rounded-2xl rounded-bl-none text-stone-400">
                    <span className="w-2 h-2 rounded-full bg-emerald-400 animate-bounce" />
                    <span className="w-2 h-2 rounded-full bg-emerald-400 animate-bounce [animation-delay:0.2s]" />
                    <span className="w-2 h-2 rounded-full bg-emerald-400 animate-bounce [animation-delay:0.4s]" />
                  </div>
                )}
              </div>

              {/* Chat Input Bar */}
              <div className="bg-[#202c33] p-2 sm:p-3 border-t border-[#2a3942] flex items-center gap-2 shrink-0">
                <input
                  type="text"
                  value={inputText}
                  onChange={(e) => setInputText(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      e.preventDefault();
                      handleSendMessage();
                    }
                  }}
                  placeholder="Ketik pesan atau angka (contoh: 1, 2, status)..."
                  className="flex-1 bg-[#2a3942] border border-transparent focus:border-emerald-500 text-white rounded-xl px-3.5 py-2 text-xs sm:text-sm placeholder-stone-400 focus:outline-none transition shadow-inner"
                />

                <button
                  type="button"
                  onClick={() => handleSendMessage()}
                  disabled={!inputText.trim() || isBotTyping}
                  className="w-10 h-10 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white flex items-center justify-center transition active:scale-95 shadow-md disabled:opacity-40 cursor-pointer"
                >
                  <Send className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Quick Testing Guide & Actions Panel */}
            <div className="w-full lg:w-80 flex flex-col gap-3 shrink-0 overflow-y-auto">
              {/* Fast Scenario Test Card */}
              <div className="bg-stone-900 border border-stone-800 rounded-2xl p-4 space-y-3">
                <div className="flex items-center gap-2 text-xs font-bold text-emerald-400">
                  <Sparkles className="w-4 h-4" />
                  <span>Skenario Pengujian Cepat</span>
                </div>
                <p className="text-[11px] text-stone-400">
                  Klik skenario di bawah untuk menguji respon bot WhatsApp secara otomatis:
                </p>

                <div className="space-y-1.5">
                  <button
                    type="button"
                    onClick={() => handleSendMessage('1')}
                    className="w-full min-h-[38px] px-3 rounded-xl bg-stone-950 border border-stone-850 hover:border-emerald-500/50 text-left text-xs font-semibold text-stone-200 flex items-center justify-between transition cursor-pointer"
                  >
                    <span>1. Buka Daftar Menu</span>
                    <ChevronRight className="w-3.5 h-3.5 text-stone-500" />
                  </button>

                  <button
                    type="button"
                    onClick={() => handleSendMessage('pesan_delivery')}
                    className="w-full min-h-[38px] px-3 rounded-xl bg-stone-950 border border-stone-850 hover:border-emerald-500/50 text-left text-xs font-semibold text-stone-200 flex items-center justify-between transition cursor-pointer"
                  >
                    <span>2. Uji Alur Delivery DQM</span>
                    <ChevronRight className="w-3.5 h-3.5 text-stone-500" />
                  </button>

                  <button
                    type="button"
                    onClick={() => handleSendMessage('pesan_takeaway')}
                    className="w-full min-h-[38px] px-3 rounded-xl bg-stone-950 border border-stone-850 hover:border-emerald-500/50 text-left text-xs font-semibold text-stone-200 flex items-center justify-between transition cursor-pointer"
                  >
                    <span>3. Uji Alur Bungkus</span>
                    <ChevronRight className="w-3.5 h-3.5 text-stone-500" />
                  </button>

                  <button
                    type="button"
                    onClick={() => handleSendMessage('5')}
                    className="w-full min-h-[38px] px-3 rounded-xl bg-stone-950 border border-stone-850 hover:border-emerald-500/50 text-left text-xs font-semibold text-stone-200 flex items-center justify-between transition cursor-pointer"
                  >
                    <span>4. Uji Formulir Pre-Order (PO)</span>
                    <ChevronRight className="w-3.5 h-3.5 text-stone-500" />
                  </button>

                  <button
                    type="button"
                    onClick={() => handleSendMessage('cek status')}
                    className="w-full min-h-[38px] px-3 rounded-xl bg-stone-950 border border-stone-850 hover:border-emerald-500/50 text-left text-xs font-semibold text-stone-200 flex items-center justify-between transition cursor-pointer"
                  >
                    <span>5. Cek Status Pesanan Realtime</span>
                    <ChevronRight className="w-3.5 h-3.5 text-stone-500" />
                  </button>
                </div>
              </div>

              {/* Bot Cloud Status Summary */}
              <div className="bg-stone-900 border border-stone-800 rounded-2xl p-4 space-y-2.5">
                <div className="text-xs font-bold text-stone-200 flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-emerald-400" />
                  <span>Spesifikasi WA Bot</span>
                </div>

                <div className="space-y-1.5 text-[11px] text-stone-400">
                  <div className="flex justify-between py-1 border-b border-stone-800">
                    <span>Database:</span>
                    <span className="font-bold text-stone-200">Google Firestore Realtime</span>
                  </div>
                  <div className="flex justify-between py-1 border-b border-stone-800">
                    <span>Target Pesanan:</span>
                    <span className="font-bold text-stone-200">orders &amp; transactions</span>
                  </div>
                  <div className="flex justify-between py-1 border-b border-stone-800">
                    <span>Min. Delivery DQM:</span>
                    <span className="font-bold text-emerald-400">{formatRupiah(settings.deliveryMinOrder || 20000)}</span>
                  </div>
                  <div className="flex justify-between py-1">
                    <span>Status Toko:</span>
                    <span className="font-bold text-emerald-400">
                      {checkStoreStatus(settings).isOpen ? 'Buka Normal' : 'Tutup'}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ========================================================
            TAB 2: PESANAN MASUK DARI WA BOT
           ======================================================== */}
        {activeTab === 'orders' && (
          <div className="flex-1 overflow-y-auto max-w-5xl mx-auto w-full space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-2 border-b border-stone-800">
              <div>
                <h3 className="font-black text-base text-white">
                  Pusat Pesanan Masuk via WA Bot Otomatis
                </h3>
                <p className="text-xs text-stone-400">
                  Pesanan yang dibuat oleh pelanggan melalui WA Bot langsung sinkron ke antrian kasir ini secara realtime
                </p>
              </div>

              <span className="text-xs font-bold px-3 py-1 rounded-xl bg-emerald-600/20 text-emerald-400 border border-emerald-500/30">
                {wabotOrders.length} Pesanan Tercatat
              </span>
            </div>

            {wabotOrders.length === 0 ? (
              <div className="p-8 text-center bg-stone-900 border border-stone-800 rounded-3xl space-y-3">
                <ShoppingBag className="w-12 h-12 text-stone-600 mx-auto" />
                <h4 className="text-sm font-bold text-stone-300">Belum Ada Pesanan dari WA Bot</h4>
                <p className="text-xs text-stone-500 max-w-md mx-auto">
                  Gunakan tab *Live Simulator WA* untuk membuat pesanan simulasi pertama. Pesanan akan otomatis muncul di sini!
                </p>
                <button
                  type="button"
                  onClick={() => setActiveTab('simulator')}
                  className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs transition"
                >
                  Buka Simulator WA
                </button>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
                {wabotOrders.map((order) => {
                  const isDeliv = order.orderType === 'DELIVERY_DQM';
                  const waNumberClean = sanitizeWhatsAppNumber(order.no_whatsapp);
                  const isCopied = copiedInvoice === order.id_transaksi;

                  return (
                    <div
                      key={order.id_transaksi}
                      className="p-4 rounded-2xl bg-stone-900 border border-stone-800 hover:border-emerald-500/40 transition shadow-lg space-y-3"
                    >
                      <div className="flex items-start justify-between gap-2">
                        <div>
                          <div className="flex items-center gap-2">
                            <span className="font-mono font-extrabold text-xs text-white">
                              {order.id_transaksi}
                            </span>
                            <button
                              type="button"
                              onClick={() => {
                                navigator.clipboard.writeText(order.id_transaksi);
                                setCopiedInvoice(order.id_transaksi);
                                setTimeout(() => setCopiedInvoice(null), 2000);
                              }}
                              className="text-stone-400 hover:text-white"
                              title="Salin No. Pesanan"
                            >
                              {isCopied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                            </button>
                          </div>
                          <div className="text-[11px] text-stone-400 mt-0.5">
                            {order.tanggal} · {order.jam} WIB
                          </div>
                        </div>

                        <span
                          className={`text-[10px] font-black uppercase px-2.5 py-1 rounded-full border ${
                            order.status === 'SELESAI'
                              ? 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30'
                              : order.status === 'SIAP'
                              ? 'bg-orange-500/20 text-orange-400 border-orange-500/30'
                              : order.status === 'DIPROSES'
                              ? 'bg-blue-500/20 text-blue-400 border-blue-500/30'
                              : 'bg-amber-500/20 text-amber-400 border-amber-500/30'
                          }`}
                        >
                          {order.status || 'MENUNGGU'}
                        </span>
                      </div>

                      <div className="p-2.5 rounded-xl bg-stone-950 border border-stone-850 text-xs space-y-1">
                        <div className="flex justify-between">
                          <span className="text-stone-400">Pemesan:</span>
                          <span className="font-bold text-stone-200">{order.nama_pelanggan}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-stone-400">WhatsApp:</span>
                          <span className="font-mono font-bold text-stone-200">{order.no_whatsapp}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-stone-400">Layanan:</span>
                          <span className={`font-bold ${isDeliv ? 'text-emerald-400' : 'text-orange-400'}`}>
                            {isDeliv ? '🛵 Delivery DQM' : '📦 Bungkus'}
                          </span>
                        </div>
                        {order.deliveryLocation && (
                          <div className="flex justify-between">
                            <span className="text-stone-400">Lokasi:</span>
                            <span className="text-stone-300 truncate max-w-[180px]">{order.deliveryLocation}</span>
                          </div>
                        )}
                      </div>

                      {/* Items */}
                      <div className="text-xs space-y-1 text-stone-300">
                        {order.items?.map((it, idx) => (
                          <div key={idx} className="flex justify-between text-[11px]">
                            <span>
                              {it.nama_produk} x{it.qty}
                            </span>
                            <span className="font-mono text-stone-400">{formatRupiah(it.subtotal)}</span>
                          </div>
                        ))}
                      </div>

                      <div className="pt-2 border-t border-stone-800 flex items-center justify-between">
                        <div>
                          <span className="text-[10px] text-stone-500 block">Total Transaksi</span>
                          <span className="text-sm font-mono font-extrabold text-orange-400">
                            {formatRupiah(order.total)}
                          </span>
                        </div>

                        <div className="flex items-center gap-1.5">
                          {onSelectTransaction && (
                            <button
                              type="button"
                              onClick={() => onSelectTransaction(order)}
                              className="px-2.5 py-1 rounded-lg bg-stone-800 hover:bg-stone-750 text-stone-300 text-[11px] font-bold"
                            >
                              Struk
                            </button>
                          )}

                          <a
                            href={`https://wa.me/${waNumberClean}?text=${encodeURIComponent(`Halo ${order.nama_pelanggan}, pesanan ${order.id_transaksi} Anda di Warung Bang Kobra sedang kami proses!`)}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="px-3 py-1 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-[11px] font-bold flex items-center gap-1"
                          >
                            <Phone className="w-3 h-3" />
                            <span>WA Pelanggan</span>
                          </a>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        )}

        {/* ========================================================
            TAB 3: KONFIGURASI & TEMPLATE BOT
           ======================================================== */}
        {activeTab === 'config' && (
          <div className="flex-1 overflow-y-auto max-w-4xl mx-auto w-full space-y-6">
            <div className="flex items-center justify-between pb-2 border-b border-stone-800">
              <div>
                <h3 className="font-black text-base text-white">
                  Pengaturan &amp; Template Pesan WA Bot
                </h3>
                <p className="text-xs text-stone-400">
                  Kelola respon otomatis, salam pembuka, dan aturan operasional asisten WhatsApp
                </p>
              </div>

              <button
                type="button"
                disabled={isSavingConfig}
                onClick={handleSaveBotConfig}
                className="px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-black text-xs shadow-lg transition active:scale-95 disabled:opacity-50 cursor-pointer"
              >
                {isSavingConfig ? 'Menyimpan...' : 'Simpan Pengaturan'}
              </button>
            </div>

            <div className="space-y-4">
              {/* Toggle Bot Aktif */}
              <div className="p-4 rounded-2xl bg-stone-900 border border-stone-800 flex items-center justify-between">
                <div>
                  <h4 className="text-xs font-bold text-white">Aktivasi Asisten WA Bot Otomatis</h4>
                  <p className="text-[11px] text-stone-400 mt-0.5">
                    Jika dinonaktifkan, pesan masuk akan dialihkan ke nomor WhatsApp kasir biasa.
                  </p>
                </div>
                <input
                  type="checkbox"
                  checked={botConfig.isEnabled}
                  onChange={(e) => setBotConfig({ ...botConfig, isEnabled: e.target.checked })}
                  className="w-5 h-5 accent-emerald-500 rounded cursor-pointer"
                />
              </div>

              {/* Bot Name & WhatsApp Number */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="text-xs font-bold text-stone-300 block mb-1">
                    Nama Bot WhatsApp *
                  </label>
                  <input
                    type="text"
                    value={botConfig.botName}
                    onChange={(e) => setBotConfig({ ...botConfig, botName: e.target.value })}
                    className="w-full bg-stone-900 border border-stone-800 rounded-xl px-3 py-2 text-xs text-white"
                  />
                </div>
                <div>
                  <label className="text-xs font-bold text-stone-300 block mb-1">
                    Nomor WhatsApp Resmi Bot *
                  </label>
                  <input
                    type="text"
                    value={botConfig.botPhoneNumber}
                    onChange={(e) => setBotConfig({ ...botConfig, botPhoneNumber: e.target.value })}
                    className="w-full bg-stone-900 border border-stone-800 rounded-xl px-3 py-2 text-xs text-white"
                  />
                </div>
              </div>

              {/* Greeting Template */}
              <div>
                <label className="text-xs font-bold text-stone-300 block mb-1">
                  Pesan Sambutan Utama (Greeting)
                </label>
                <textarea
                  rows={4}
                  value={botConfig.greetingMessage}
                  onChange={(e) => setBotConfig({ ...botConfig, greetingMessage: e.target.value })}
                  className="w-full bg-stone-900 border border-stone-800 rounded-xl p-3 text-xs text-white font-mono"
                />
              </div>

              {/* Closed Message */}
              <div>
                <label className="text-xs font-bold text-stone-300 block mb-1">
                  Pesan Saat Toko Tutup / Di Luar Jam Kerja
                </label>
                <textarea
                  rows={3}
                  value={botConfig.closedMessage}
                  onChange={(e) => setBotConfig({ ...botConfig, closedMessage: e.target.value })}
                  className="w-full bg-stone-900 border border-stone-800 rounded-xl p-3 text-xs text-white font-mono"
                />
              </div>

              {/* Fallback Auto Reply Unknown */}
              <div>
                <label className="text-xs font-bold text-stone-300 block mb-1">
                  Respon Otomatis Saat Pesan Tidak Dipahami
                </label>
                <textarea
                  rows={2}
                  value={botConfig.autoReplyUnknown}
                  onChange={(e) => setBotConfig({ ...botConfig, autoReplyUnknown: e.target.value })}
                  className="w-full bg-stone-900 border border-stone-800 rounded-xl p-3 text-xs text-white font-mono"
                />
              </div>
            </div>
          </div>
        )}

        {/* ========================================================
            TAB 4: INTEGRASI GATEWAY & WEBHOOK
           ======================================================== */}
        {activeTab === 'webhook' && (
          <div className="flex-1 overflow-y-auto max-w-4xl mx-auto w-full space-y-5">
            <div>
              <h3 className="font-black text-base text-white">
                Spesifikasi Integrasi Gateway &amp; Webhook API
              </h3>
              <p className="text-xs text-stone-400">
                Gunakan format webhook berikut untuk menghubungkan server WhatsApp gateway nyata (Fonnte, Wablas, Baileys, atau WhatsApp Cloud API)
              </p>
            </div>

            <div className="p-4 rounded-2xl bg-stone-900 border border-stone-800 space-y-3">
              <div className="flex items-center gap-2 text-xs font-bold text-emerald-400">
                <ShieldCheck className="w-4 h-4" />
                <span>Format Payload Masuk (Inbound Webhook)</span>
              </div>
              <pre className="p-3 bg-stone-950 rounded-xl text-[11px] font-mono text-stone-300 overflow-x-auto border border-stone-850">
{`POST /api/wabot/webhook
Content-Type: application/json

{
  "sender": "6281298765432",
  "name": "Budi Santoso",
  "message": "1",
  "timestamp": 1728182400
}`}
              </pre>
            </div>

            <div className="p-4 rounded-2xl bg-stone-900 border border-stone-800 space-y-3">
              <div className="flex items-center gap-2 text-xs font-bold text-orange-400">
                <FileText className="w-4 h-4" />
                <span>Format Respon Balasan Bot (Outbound Reply)</span>
              </div>
              <pre className="p-3 bg-stone-950 rounded-xl text-[11px] font-mono text-stone-300 overflow-x-auto border border-stone-850">
{`{
  "reply": "🍽️ DAFTAR MENU RESMI WARUNG BANG KOBRA\\n1. Mi Rendang Kobra - Rp15.000\\n...",
  "quickReplies": ["1", "2", "3", "6"],
  "targetPhone": "6281298765432"
}`}
              </pre>
            </div>
          </div>
        )}

        {/* ========================================================
            TAB 5: AUDIT LOG CLOUD
           ======================================================== */}
        {activeTab === 'logs' && (
          <div className="flex-1 overflow-y-auto max-w-4xl mx-auto w-full space-y-3">
            <div className="pb-2 border-b border-stone-800">
              <h3 className="font-black text-base text-white">
                Log Riwayat Aktivitas WA Bot di Cloud Firestore
              </h3>
              <p className="text-xs text-stone-400">
                Seluruh aktivitas pesanan baru, pre-order, dan perubahan konfigurasi tercatat otomatis
              </p>
            </div>

            {auditLogs.length === 0 ? (
              <div className="p-6 text-center text-xs text-stone-500 bg-stone-900 rounded-2xl border border-stone-800">
                Belum ada log aktivitas WA Bot di Firestore.
              </div>
            ) : (
              <div className="space-y-2">
                {auditLogs.map((log) => (
                  <div
                    key={log.id}
                    className="p-3 rounded-xl bg-stone-900 border border-stone-850 flex items-center justify-between text-xs gap-3"
                  >
                    <div>
                      <div className="font-bold text-stone-200">{log.action}</div>
                      <div className="text-[11px] text-stone-400">{log.details}</div>
                    </div>
                    <div className="text-right shrink-0">
                      <span className="text-[10px] text-stone-500 font-mono block">
                        {new Date(log.timestamp).toLocaleTimeString('id-ID')}
                      </span>
                      <span className="text-[10px] px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 font-bold">
                        {log.actor || log.user || 'WA BOT'}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};
